from .aluno import Aluno
from .documento import Documento
from .responsavel import Responsavel
from .diretor import Diretor
from .endereco import Endereco
from .documentos import DocumentosAluno
from .habitacional import SituacaoHabitacional
from .bens_domicilio import BensDomicilio
from .familia import MembroFamiliar
from .pessoa_autorizada import PessoaAutorizada