# Generated by Django 5.2.6 on 2025-10-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BensDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('televisao', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('banheiro', models.IntegerField(default=0)),
                ('automovel', models.IntegerField(default=0)),
                ('empregada_domestica', models.IntegerField(default=0)),
                ('maquina_lavar', models.BooleanField(default=False)),
                ('dvd', models.BooleanField(default=False)),
                ('geladeira', models.BooleanField(default=False)),
                ('freezer', models.BooleanField(default=False)),
                ('lava_louca', models.BooleanField(default=False)),
                ('forno_microondas', models.BooleanField(default=False)),
                ('motocicleta', models.BooleanField(default=False)),
                ('secadora_roupa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_moradia', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('kitnet', 'Kitnet'), ('outros', 'Outros')], max_length=20)),
                ('situacao_moradia', models.CharField(choices=[('propria', 'Própria'), ('alugada', 'Alugada'), ('cedida', 'Cedida'), ('financiada', 'Financiada')], max_length=20)),
                ('agua_encanada', models.BooleanField(default=True)),
                ('energia_eletrica', models.BooleanField(default=True)),
                ('esgoto', models.BooleanField(default=True)),
                ('coleta_lixo', models.BooleanField(default=True)),
                ('pavimentacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_familiar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficio_social', models.BooleanField(default=False)),
                ('tipo_beneficio', models.CharField(blank=True, max_length=100, null=True)),
                ('bens_domicilio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creche.bensdomicilio')),
                ('habitacional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creche.habitacional')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profissao', models.CharField(max_length=100)),
                ('local_trabalho', models.CharField(blank=True, max_length=200, null=True)),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creche.endereco')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creche.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('certidao_nascimento', models.FileField(blank=True, null=True, upload_to='documentos/certidoes/')),
                ('cartao_vacina', models.FileField(blank=True, null=True, upload_to='documentos/vacinas/')),
                ('comprovante_residencia_url', models.FileField(blank=True, null=True, upload_to='documentos/comprovantes/')),
                ('foto_3x4_url', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('possui_deficiencia', models.BooleanField(default=False)),
                ('classificacao_deficiencia', models.JSONField(blank=True, default=list)),
                ('laudo_medico', models.FileField(blank=True, null=True, upload_to='documentos/laudos/')),
                ('medicamentos', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('observacoes_medicas', models.TextField(blank=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creche.endereco')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creche.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_autorizadas', to='creche.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='creche.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certidao_nascimento', models.FileField(blank=True, null=True, upload_to='documentos/certidoes/')),
                ('cartao_vacina', models.FileField(blank=True, null=True, upload_to='documentos/vacinas/')),
                ('comprovante_residencia', models.FileField(blank=True, null=True, upload_to='documentos/comprovantes/')),
                ('foto_3x4', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('laudo_medico', models.FileField(blank=True, null=True, upload_to='documentos/laudos/')),
                ('rg_responsavel', models.FileField(blank=True, null=True, upload_to='documentos/rg/')),
                ('cpf_responsavel', models.FileField(blank=True, null=True, upload_to='documentos/cpf/')),
                ('comprovante_renda', models.FileField(blank=True, null=True, upload_to='documentos/renda/')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_completos', to='creche.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_contratacao', models.DateField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creche.endereco')),
            ],
        ),
    ]
