# Generated by Django 5.2.6 on 2025-10-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('masc', 'Masculino'), ('fem', 'Feminino')], max_length=50)),
                ('raca', models.CharField(choices=[('branca', 'Branca'), ('parda', 'Pardo'), ('negra', 'Negra')], max_length=25)),
                ('gemeos', models.CharField(blank=True, max_length=255, null=True)),
                ('irmao_na_creche', models.BooleanField(blank=True, default=False, null=True)),
                ('cadastro_nacional_de_saude', models.CharField(max_length=15)),
                ('unidade_de_saude', models.CharField(max_length=10)),
                ('problemas_de_saude', models.BooleanField(blank=True, default=False, null=True)),
                ('restricao_alimentar', models.TextField(blank=True, null=True)),
                ('alergia', models.TextField(blank=True, null=True)),
                ('deficiencias_multiplas', models.TextField(blank=True, null=True)),
                ('mobilidade_reduzida', models.CharField(blank=True, choices=[('temp', 'TEMPORÁRIA'), ('perm', 'PERMANENTE')], max_length=25, null=True)),
                ('crianca_alvo_educacao_especial', models.TextField(blank=True, null=True)),
                ('classificacoes', models.JSONField(blank=True, default=list, verbose_name='Classificações Especiais')),
                ('responsavel_recebe_auxilio', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.CharField(blank=True, max_length=100, null=True)),
                ('renda_familiar_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprovante_residencia_url', models.FileField(upload_to='documentos/residencial/')),
                ('certidao_nascimento', models.FileField(upload_to='documentos/certidoes/')),
                ('ativo', models.BooleanField(default=True)),
                ('serie_cursar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Série que irá cursar')),
                ('ano_cursar', models.CharField(blank=True, help_text='Ex: 2025', max_length=4, null=True, verbose_name='Ano de Início')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField()),
                ('local_de_trabalho', models.CharField(max_length=255)),
                ('dados_extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BensDomicilio',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='creche.aluno', verbose_name='Aluno')),
                ('tv', models.BooleanField(default=False, verbose_name='TV')),
                ('dvd', models.BooleanField(default=False, verbose_name='DVD')),
                ('radio', models.BooleanField(default=False, verbose_name='Rádio')),
                ('computador', models.BooleanField(default=False, verbose_name='Computador')),
                ('notebook', models.BooleanField(default=False, verbose_name='Notebook')),
                ('telefone_fixo', models.BooleanField(default=False, verbose_name='Telefone Fixo')),
                ('telefone_celular', models.BooleanField(default=False, verbose_name='Telefone Celular')),
                ('tablet', models.BooleanField(default=False, verbose_name='Tablet')),
                ('internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('tv_assinatura', models.BooleanField(default=False, verbose_name='TV por Assinatura')),
                ('fogao', models.BooleanField(default=False, verbose_name='Fogão')),
                ('geladeira', models.BooleanField(default=False, verbose_name='Geladeira')),
                ('freezer', models.BooleanField(default=False, verbose_name='Freezer')),
                ('micro_ondas', models.BooleanField(default=False, verbose_name='Micro-Ondas')),
                ('maquina_lavar_roupa', models.BooleanField(default=False, verbose_name='Máquina de Lavar Roupa')),
                ('ar_condicionado', models.BooleanField(default=False, verbose_name='Ar Condicionado')),
                ('bicicleta', models.BooleanField(default=False, verbose_name='Bicicleta')),
                ('moto', models.BooleanField(default=False, verbose_name='Moto')),
                ('automovel', models.BooleanField(default=False, verbose_name='Automóvel')),
            ],
            options={
                'verbose_name': 'Bens no Domicílio',
                'verbose_name_plural': 'Bens no Domicílio',
            },
        ),
        migrations.CreateModel(
            name='DocumentosAluno',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='creche.aluno', verbose_name='Aluno')),
                ('certidao_nascimento_matricula', models.CharField(max_length=50, verbose_name='Matrícula da Certidão de Nascimento')),
                ('municipio_nascimento', models.CharField(max_length=100, verbose_name='Município do Nascimento')),
                ('municipio_registro', models.CharField(max_length=100, verbose_name='Município do Registro')),
                ('cartorio_registro', models.CharField(max_length=255, verbose_name='Cartório de Registro')),
                ('arquivo_certidao', models.FileField(upload_to='documentos/certidoes/', verbose_name='Arquivo da Certidão (PDF/Imagem)')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('data_emissao_rg', models.DateField(verbose_name='Data de Emissão do RG')),
                ('orgao_emissor_rg', models.CharField(max_length=50, verbose_name='Órgão Emissor do RG')),
            ],
            options={
                'verbose_name': 'Documentos da Criança',
                'verbose_name_plural': 'Documentos das Crianças',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='creche.aluno', verbose_name='Aluno')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('ponto_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço da Criança',
                'verbose_name_plural': 'Endereços das Crianças',
            },
        ),
        migrations.CreateModel(
            name='SituacaoHabitacional',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='creche.aluno', verbose_name='Aluno')),
                ('tipo_imovel', models.CharField(choices=[('propria', 'CASA PRÓPRIA'), ('cedida', 'CASA CEDIDA'), ('alugada', 'CASA ALUGADA')], max_length=10, verbose_name='Tipo de Imóvel')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Aluguel (R$)')),
                ('numero_comodos', models.PositiveSmallIntegerField(verbose_name='Nº de Cômodos')),
                ('piso_cimento', models.BooleanField(default=False, verbose_name='Piso de Cimento')),
                ('piso_lajota', models.BooleanField(default=False, verbose_name='Piso de Lajota')),
                ('piso_chao_batido', models.BooleanField(default=False, verbose_name='Piso de Chão Batido')),
                ('tipo_moradia_estrutura', models.JSONField(default=list, verbose_name='Estrutura de Moradia (Paredes/Cobertura)')),
                ('saneamento_fossa', models.BooleanField(default=False, verbose_name='Fossa')),
                ('saneamento_cifon', models.BooleanField(default=False, verbose_name='Cifon')),
                ('energia_eletrica', models.BooleanField(default=False, verbose_name='Energia Elétrica')),
                ('agua_encanada', models.BooleanField(default=False, verbose_name='Água Encanada')),
            ],
            options={
                'verbose_name': 'Situação Habitacional e Sanitária',
                'verbose_name_plural': 'Situações Habitacionais e Sanitárias',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('residencia', 'Comprovante de Residência'), ('renda', 'Comprovante de Renda'), ('identidade', 'Documento de Identidade'), ('outro', 'Outro')], max_length=50)),
                ('arquivo', models.FileField(upload_to='documentos/outros/')),
                ('baixado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='creche.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='MembroFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('idade', models.PositiveSmallIntegerField(verbose_name='Idade')),
                ('parentesco', models.CharField(help_text='Ex: Mãe, Pai, Irmão, Avó, Próprio Aluno.', max_length=50, verbose_name='Grau de Parentesco')),
                ('situacao_escolar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação Escolar')),
                ('situacao_emprego', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação de Emprego')),
                ('renda_bruta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salários / Aposentadorias / Pensões e Outros (Valor Bruto R$)')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_familiar', to='creche.aluno', verbose_name='Aluno Matrícula')),
            ],
            options={
                'verbose_name': 'Membro Familiar',
                'verbose_name_plural': 'Membros Familiares',
                'ordering': ['-renda_bruta', 'idade'],
            },
        ),
        migrations.CreateModel(
            name='PessoaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('fone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('e_responsavel_legal', models.BooleanField(default=False, verbose_name='É Responsável Legal Cadastrado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizados_retirada', to='creche.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Pessoa Autorizada para Retirada',
                'verbose_name_plural': 'Pessoas Autorizadas para Retirada',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(related_name='alunos', to='creche.responsavel'),
        ),
    ]
