# Generated by Django 5.2.6 on 2025-09-18 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField()),
                ('dados_extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('masc', 'Masculino'), ('fem', 'Feminino')], max_length=50)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.CharField(blank=True, max_length=100, null=True)),
                ('renda_familiar_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprovante_residencia_url', models.FileField(upload_to='documentos/residencial/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsaveis', models.ManyToManyField(related_name='alunos', to='creche.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('residencia', 'Comprovante de Residência'), ('renda', 'Comprovante de Renda'), ('identidade', 'Documento de Identidade'), ('outro', 'Outro')], max_length=50)),
                ('arquivo', models.FileField(upload_to='documentos/outros/')),
                ('baixado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='creche.aluno')),
                ('baixado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
