# Generated by Django 5.2.6 on 2025-10-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='certidao_nascimento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/certidoes/'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='comprovante_residencia_url',
            field=models.FileField(blank=True, null=True, upload_to='documentos/residencial/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/outros/'),
        ),
        migrations.AlterField(
            model_name='documentosaluno',
            name='arquivo_certidao',
            field=models.FileField(blank=True, null=True, upload_to='documentos/certidoes/', verbose_name='Arquivo da Certidão (PDF/Imagem)'),
        ),
    ]
