# Generated by Django 5.2.6 on 2025-09-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creche', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='baixado_por',
        ),
    ]
